language: android
android:
    components:
        - tools
        - platform-tools
        - build-tools-23.0.3
        - android-23
        - extra-android-m2repository

jdk:
- oraclejdk8

before_script:
- chmod +x gradlew

script:
- ./gradlew assembleDebug --stacktrace

env:
- USER=me
- APIKEY=fakepassword